In [6]:
with open("../chinese_freq.txt", "r", encoding="utf-8") as f:
    lines = f.read().splitlines()
freqs = []
words = []
translations = []
for line in lines:
    chunks = line.split("\t")
    words.append(chunks[1])
    freqs.append(chunks[2])
    translations.append(chunks[-1])

In [166]:
with open("../frequency.txt", "r", encoding="utf-8") as f:
    lines = f.read().splitlines()
freqs = []
words = []
for line in lines:
    chunks = line.split()
    words.append(chunks[0])
    freqs.append(chunks[1])

In [24]:
top_25 = 33+1
top_50 = 152+1
top_75 = 483+1

In [7]:
from collections import defaultdict
# Create dict for text into strokes translation and vice versa
with open("../vocab/zh2letter.txt", 'r', encoding="utf-8") as f:
    conversions = f.read()

conversions = conversions.splitlines()
dic = defaultdict(str)
st2zh = defaultdict(str)
for line in conversions:
    chinese_char, strokes = line.split()
    dic[chinese_char] = strokes
    st2zh[strokes] = chinese_char

In [31]:
from fairseq.models.lstm import LSTMModel
path = "C:/Users/xk_20/Documents/Code/CS4248/StrokeNet/checkpoints/NIST/lstm_trad"
bpe_path = "C:/Users/xk_20/Documents/Code/CS4248/StrokeNet/data/NIST/trad/bpe"
lstm_trad = LSTMModel.from_pretrained(
  path,
  checkpoint_file='checkpoint_best.pt',
  data_name_or_path=bpe_path + '/bin',
  bpe='subword_nmt',
  bpe_codes=bpe_path + '/joint.code',
  lang_dict=bpe_path + '/bin/langs.file'
).eval()

===Jit: state["model"] does not contain key "_metadata"=====
===Jit: we will be filling in with current model's meta-data instead.


In [26]:
from fairseq.models.lstm import LSTMModel
path = "C:/Users/xk_20/Documents/Code/CS4248/StrokeNet/checkpoints/NIST/lstm_simp"
bpe_path = "C:/Users/xk_20/Documents/Code/CS4248/StrokeNet/data/NIST/simp_original/bpe"
lstm_simp = LSTMModel.from_pretrained(
  path,
  checkpoint_file='checkpoint_best.pt',
  data_name_or_path=bpe_path + '/bin',
  bpe='subword_nmt',
  bpe_codes=bpe_path + '/joint.code',
  lang_dict=bpe_path + '/bin/langs.file'
).eval()

===Jit: state["model"] does not contain key "_metadata"=====
===Jit: we will be filling in with current model's meta-data instead.


In [17]:
import opencc
converter = opencc.OpenCC('s2t.json')

In [254]:
sentence = "柬埔寨"
strokes = ""
for word in sentence:
    strokes += dic[word] + " "
strokes

'eaioteatn eadeaseeao ooheeaaetnerto '

In [111]:
sentence = "钠是一种金属元素"
sentence = "伏特在19世纪初发明了电池后，各国化学家纷纷利用电池分解水成功。英国化学家汉弗里·戴维坚持不懈地从事于利用电池分解各种物质的实验研究。"
# sentence = converter.convert(sentence)
strokes = ""
for word in sentence:
    strokes += dic[word] + " "
strokes

'taetno teadeaeero etaeae   eaaef lldiec ohatost lthno aieetsee hr aieec oodsac tteaie  thnaie aieeaeoe tatc ootohhre oohetktttn lldtnst lldtnst teatoar tseea aieec oodsac tnst thtseeastteea rhtn etsuto eadst  eaaaietn aieeaeoe tatc ootohhre oohetktttn oodhn iebta aieeaee1  eaeaieaeeaaetouto lldtaoeeeae aahneae erdeaeero etao ooathtseeastteea eadsac totn1 eaieieer eer1 teatoar tseea aieec oodsac tnst thtseeastteea thnaie teatoaiea teadtstt tteaaito taieetso oohooeto ibdtneoote etaieeeta oohtotv  '

In [114]:
sample = lstm_simp.apply_bpe(strokes)

In [ ]:
simp_many = []
for i,word in enumerate(words):
    strokes = dic[word]
    print(word, lstm_simp.apply_bpe(strokes))
    tok = lstm_simp.apply_bpe(strokes)
    if len(tok.split(" ")) > 1:
        simp_many.append(i)

In [ ]:
trad_many = []
for i, word in enumerate(words):
    word = converter.convert(word)
    strokes = dic[word]
    print(word, lstm_trad.apply_bpe(strokes))
    tok = lstm_trad.apply_bpe(strokes)
    if len(tok.split(" ")) > 1:
        trad_many.append(i)

In [282]:
lstm_trad.apply_bpe(dic[converter.convert("艚")])

'ttsoe@@ oeaie@@ aaeaiee'

In [287]:
lstm_simp.apply_bpe(dic["舟"])

'ttsoeo'

In [295]:
st2zh["eaaeaiee"]

'昔'

In [269]:
converter.convert("铠")

'鎧'

In [233]:
set(simp_many).difference(set(trad_many))

{2554,
 2709,
 2730,
 2735,
 2830,
 2877,
 2879,
 2882,
 2908,
 2962,
 2993,
 3029,
 3030,
 3121,
 3128,
 3156,
 3161,
 3178,
 3196,
 3227,
 3261,
 3349,
 3356,
 3429,
 3504,
 3545,
 3553,
 3559,
 3573,
 3621,
 3622,
 3623,
 3625,
 3635,
 3639,
 3659,
 3665,
 3666,
 3685,
 3726,
 3733,
 3739,
 3766,
 3768,
 3774,
 3784,
 3792,
 3812,
 3816,
 3839,
 3847,
 3852,
 3859,
 3930,
 3932,
 3933,
 3943,
 3948,
 3952,
 3968,
 3984,
 3985,
 3986,
 3987,
 3988,
 3989,
 3990,
 3995,
 4007,
 4028,
 4029,
 4030,
 4044,
 4071,
 4078,
 4083,
 4084,
 4101,
 4103,
 4105,
 4123,
 4124,
 4125,
 4126,
 4127,
 4128,
 4129,
 4130,
 4131,
 4132,
 4133,
 4138,
 4151,
 4152,
 4158,
 4181,
 4188,
 4213,
 4221,
 4232,
 4244,
 4264,
 4265,
 4266,
 4276,
 4278,
 4279,
 4292,
 4295,
 4299,
 4309,
 4310,
 4318,
 4320,
 4322,
 4334,
 4342,
 4362,
 4368,
 4369,
 4371,
 4373,
 4374,
 4375,
 4380,
 4381,
 4382,
 4384,
 4385,
 4386,
 4387,
 4388,
 4389,
 4390,
 4391,
 4392,
 4393,
 4397,
 4407,
 4408,
 4409,
 4410,
 4418,

In [ ]:
sentence = "这里有两段故事——其中的一段是在柬埔寨。 我们选择的村庄没有电，没有自来水，没有电视，也没有电话， 但是现在却有了宽带互联网。"
translated = 'And these are two anecdotes -- one was in Cambodia, in a village that has no electricity, no water, no television, no telephone, but has broadband Internet now.'
import evaluate

metric = evaluate.load("sacrebleu")
trad_result = metric.compute(predictions=[lstm_trad.translate([converter.convert(sentence)])], references=[translated])
simp_result = metric.compute(predictions=[lstm_simp.translate([sentence])], references=[translated])

In [206]:
converter.convert(sentence)

'這裏有兩段故事——其中的一段是在柬埔寨。 我們選擇的村莊沒有電，沒有自來水，沒有電視，也沒有電話， 但是現在卻有了寬帶互聯網。'

In [279]:
t = ""
for word in converter.convert("夕阳下的湖面，波光粼粼的，十分好看。"):
    t += dic[word] + " "
t

'tho paaieeetstt eao taieetso oodeaaietsee etaiaaeee  oodhtahn aotetc oteatothoelagg oteatothoelagg taieetso  ea1 tnst gtehre teetaieee  '

In [222]:
a = lstm_trad.translate([t])[0]
a

Data type of indices: int64
Data type of num_tokens_vec: int64
Data type of max_tokens: <class 'int'>
Data type of max_sentences: <class 'int'>
Data type of bsz_mult: <class 'int'>


'Cambodia, Cambodia.'

In [280]:
b = lstm_simp.translate([t])[0]
b

Data type of indices: int64
Data type of num_tokens_vec: int64
Data type of max_tokens: <class 'int'>
Data type of max_sentences: <class 'int'>
Data type of bsz_mult: <class 'int'>


'This is a very good view of the lake of the laza of the lake.'

In [ ]:
simp_result

In [115]:
original = "".join(sample.split()).replace("@", "")
print(st2zh[original])
splits = sample.split()
print(splits)
for split in splits:
    print(st2zh[split.strip("@")])


['taetno', 'teadeaeero', 'etaeae', 'eaaef', 'lldiec', 'ohatost', 'lthno', 'aieetsee', 'hr', 'aieec', 'oodsac', 'tteaie', 'thnaie', 'aieeaeoe', 'tatc', 'ootohhre', 'oohetktttn', 'lldtnst', 'lldtnst', 'teatoar', 'tseea', 'aieec', 'oodsac', 'tnst', 'thtseeastteea', 'rhtn', 'etsuto', 'eadst', 'eaaaietn', 'aieeaeoe', 'tatc', 'ootohhre', 'oohetktttn', 'oodhn', 'iebta', 'aieeaee1', 'eaeaieaeeaaetouto', 'lldtaoeeeae', 'aahneae', 'erdeaeero', 'etao', 'ooa@@', 'thtseeastteea', 'eadsac', 'totn1', 'eaieieer', 'eer1', 'teatoar', 'tseea', 'aieec', 'oodsac', 'tnst', 'thtseeastteea', 'thnaie', 'teatoaiea', 'teadtstt', 'tteaaito', 'taieetso', 'oohooeto', 'ibdtneoote', 'etaieeeta', 'oohtotv']
伏
特
在
世
纪
初
发
明
了
电
池
后
各
国
化
学
家
纷
纷
利
用
电
池
分
解
水
成
功
英
国
化
学
家
汉
弗
里
戴
维
坚
持
不
忄
解
地
从
事
于
利
用
电
池
分
解
各
种
物
质
的
实
验
研
究


In [113]:
lstm_simp.translate([strokes])

Data type of indices: int64
Data type of num_tokens_vec: int64
Data type of max_tokens: <class 'int'>
Data type of max_sentences: <class 'int'>
Data type of bsz_mult: <class 'int'>


['And in the beginning of the first time in the beginning of the 20th century, the chemists were using batteries to be able to cut the water from the batteries to the British National Academy of UK in the United Kingdom, and in the United Kingdom of the United Kingdom.']

In [98]:
lstm_trad.apply_bpe(strokes)

'toeeaotd@@ as@@ to aieeeaetn e teatoteaieeeae tneeaote ietaodtoaiaaetsaieaeo eetc0 eeaellorto '

In [99]:
lstm_trad.translate([strokes])

Data type of indices: int64
Data type of num_tokens_vec: int64
Data type of max_tokens: <class 'int'>
Data type of max_sentences: <class 'int'>
Data type of bsz_mult: <class 'int'>


["It's a metal metal."]

In [37]:
trad_strokes = []
simp_strokes = []

for word in list(st2zh.keys()):
    strokes = lstm_simp.apply_bpe(word)
    splits = strokes.split()
    if len(splits) > 1: simp_strokes.append(strokes)
    strokes = lstm_trad.apply_bpe(word)
    splits = strokes.split()
    if len(splits) > 1: trad_strokes.append(strokes)

In [149]:
import random
samples = random.sample(simp_strokes, 5)
for sample in samples:
    original = "".join(sample.split()).replace("@", "")
    print(st2zh[original])
    splits = sample.split()
    print(splits)
    for split in splits:
        print(st2zh[split.strip("@")])

踴
['aieaead@@', 'hoaieeast']

勇
諃
['oee@@', 'eaiee@@', 'ato@@', 'eatn']



木
惪
['eaaieeee@@', 'ouoo']
直
心
穸
['oohto@@', 'tho']

夕
餪
['tooi@@', 'eem@@', 'oe@@', 'tas@@', 'aa@@', 'etn']


亠





In [255]:
lstm_simp.encode("eaioteatn eadeaseeao ooheeaaetnerto")

tensor([ 7148,  2185,  3987, 13492, 20226, 13154,     2])

In [256]:
lstm_trad.encode("eaioteatn eadeaseeao ooheeaaetnerto")

tensor([19242,  4234, 13588, 20531, 14413,     2])

In [42]:
st2zh["eaaeedtetn"]

''

In [55]:
lstm_simp.translate(["gtesac"])

Data type of indices: int64
Data type of num_tokens_vec: int64
Data type of max_tokens: <class 'int'>
Data type of max_sentences: <class 'int'>
Data type of bsz_mult: <class 'int'>


['She was her her. She was her.']

In [56]:
lstm_trad.translate(["gtesac"])

Data type of indices: int64
Data type of num_tokens_vec: int64
Data type of max_tokens: <class 'int'>
Data type of max_sentences: <class 'int'>
Data type of bsz_mult: <class 'int'>


['She was her. She was her.']

In [5]:
import torch
sentence = "aeeeaeee aotohaieasa oytaseeetero oytaseeetero ， eaaietc aieeaee1 eaaeeetottea 。 taieetso etaiethtseea aeeeaeee aotohaieasa eaaoheatn eaeoteea loaseetctc etasee teoteoiebat ee odthtn oeotdaeaie etaeae oetoown tna loaie aee taieetso eatotv1 tneelo ， terduto eaaieeeeto aieeeaetn aeeeaeee aotohaieasa eteaieutoouoo oodtaieeoesttetn 。"

# Get token ids
tokens = lstm.encode(sentence)
token_len = len(tokens)

# Convert to input requirement
tokens = torch.tensor([tokens.numpy()])

# get encoder
encoder = lstm.get_submodule("models.0.encoder")

# get output
encoded = encoder(tokens, torch.Tensor([token_len]))

attention = lstm.get_submodule("models.0.decoder.attention")
decoder = lstm.get_submodule("models.0.decoder")

C:\Users\xk_20\AppData\Local\Temp\ipykernel_18980\923119910.py:9: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at ..\torch\csrc\utils\tensor_new.cpp:248.)
  tokens = torch.tensor([tokens.numpy()])


In [6]:
encoder

LSTMEncoder(
  (dropout_in_module): FairseqDropout()
  (dropout_out_module): FairseqDropout()
  (embed_tokens): Embedding(23329, 512, padding_idx=1)
  (lstm): LSTM(512, 512)
)

In [7]:
# LSTM weights
list(encoder.get_submodule("lstm").parameters())

[Parameter containing:
 tensor([[ 0.3972,  0.1230,  0.0320,  ..., -0.2124, -0.0334,  0.3662],
         [ 0.7861,  0.0558, -0.1696,  ...,  0.5332,  0.2297,  0.1222],
         [ 0.1328,  0.0801, -0.2139,  ..., -0.0578,  0.0297,  0.1720],
         ...,
         [-0.0952,  0.0209,  0.0868,  ...,  0.0665, -0.1107, -0.0257],
         [ 0.0182,  0.2108, -0.1046,  ...,  0.1218, -0.1348,  0.0806],
         [ 0.2224,  0.0419, -0.0886,  ..., -0.0465, -0.1129, -0.3384]],
        requires_grad=True),
 Parameter containing:
 tensor([[-0.0368,  0.1473,  0.1625,  ..., -0.2269,  0.0818, -0.3306],
         [-0.0143, -0.1036,  0.0038,  ..., -0.0629,  0.1381, -0.1331],
         [-0.0342,  0.0387,  0.0382,  ..., -0.0023, -0.1389,  0.0848],
         ...,
         [ 0.2449,  0.0371, -0.1398,  ...,  0.0485,  0.0908,  0.0790],
         [ 0.1252,  0.2656, -0.0487,  ..., -0.1017, -0.5576,  0.2063],
         [ 0.2178, -0.1361, -0.0264,  ...,  0.0380,  0.1033, -0.0215]],
        requires_grad=True),
 Parameter con

In [8]:
# Token Embeddings weights embedding[token_id] = token_embedding
embeddings = list(encoder.get_submodule("embed_tokens").parameters())
embeddings

[Parameter containing:
 tensor([[ 0.0626, -0.0757,  0.0169,  ..., -0.0498,  0.1516, -0.0409],
         [ 0.0626, -0.0757,  0.0169,  ..., -0.0498,  0.1516, -0.0409],
         [-0.1069, -0.0035, -0.0381,  ...,  0.0343,  0.2073, -0.0552],
         ...,
         [ 0.0626, -0.0757,  0.0169,  ..., -0.0498,  0.1516, -0.0409],
         [ 0.0626, -0.0757,  0.0169,  ..., -0.0498,  0.1516, -0.0409],
         [-0.0088,  0.0045, -0.0016,  ...,  0.0061, -0.0041, -0.0017]],
        requires_grad=True)]

In [34]:
for word in sentence.split():
    print(st2zh[word], end="")

非常谢谢克里斯的确非常荣幸能有第二次站在这个台上的机会我真是非常感激

In [36]:
embeds = []
words = []
for token in tokens[0]:
    embeds.append(embeddings[0][token.numpy()])
    words.append(st2zh[lstm.decode(torch.tensor([token]))])

In [40]:
dic[""]

'gte'

In [29]:
lstm.decode(torch.tensor([tokens[0][0]]))

'aeeeaeee'

In [52]:
attention.get_submodule("input_proj").weight

Parameter containing:
tensor([[ 0.0436, -0.0187, -0.0006,  ..., -0.0314, -0.0314, -0.0040],
        [-0.0151, -0.0518, -0.0054,  ...,  0.0010, -0.0205,  0.0126],
        [ 0.0066,  0.0182, -0.0159,  ..., -0.0102,  0.0087, -0.0757],
        ...,
        [ 0.0047, -0.0118, -0.0303,  ...,  0.0219, -0.0080, -0.0251],
        [ 0.0124,  0.0779, -0.0190,  ...,  0.0056, -0.0512,  0.0226],
        [-0.0121,  0.0174, -0.0286,  ...,  0.0104,  0.0126, -0.0388]],
       requires_grad=True)

In [48]:
attention.get_submodule("output_proj").weight

Parameter containing:
tensor([[ 3.5828e-02,  1.1627e-02,  3.9612e-02,  ...,  3.2013e-02,
         -1.0663e-01, -1.1843e-04],
        [ 3.5980e-02, -3.6841e-01,  2.8671e-02,  ...,  5.2547e-04,
         -1.3989e-01, -3.4131e-01],
        [-1.3818e-01, -2.4268e-01, -2.3308e-03,  ..., -1.3867e-01,
          9.1064e-02, -2.7847e-02],
        ...,
        [-1.9788e-01, -2.7246e-01,  8.2092e-02,  ...,  5.2856e-02,
         -1.5222e-01, -8.3740e-02],
        [ 1.1093e-02,  1.1420e-01, -1.5381e-02,  ..., -8.8959e-03,
          1.3049e-01,  1.2769e-01],
        [ 7.1068e-03, -1.7334e-01, -8.5815e-02,  ...,  1.6479e-02,
         -4.0924e-02, -6.8665e-02]], requires_grad=True)

In [46]:
encoder

LSTMEncoder(
  (dropout_in_module): FairseqDropout()
  (dropout_out_module): FairseqDropout()
  (embed_tokens): Embedding(23329, 512, padding_idx=1)
  (lstm): LSTM(512, 512)
)

In [45]:
decoder

LSTMDecoder(
  (dropout_in_module): FairseqDropout()
  (dropout_out_module): FairseqDropout()
  (embed_tokens): Embedding(23329, 512, padding_idx=1)
  (layers): ModuleList(
    (0): LSTMCell(1024, 512)
  )
  (attention): AttentionLayer(
    (input_proj): Linear(in_features=512, out_features=512, bias=False)
    (output_proj): Linear(in_features=1024, out_features=512, bias=False)
  )
)

In [ ]:
sentence = "aieeaee1 aieeaee1 asdasdasf"
s = lstm.tokenize(sentence)
a = lstm.apply_bpe(s)
lstm.binarize(a)

In [ ]:
s,a